# -*- coding: utf-8 -*-
"""Random Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpc9L0bj5T90XaqmS3QWyPBeYG8xFFfs
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

dir(digits)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.gray()
for i in range(4):
  plt.matshow(digits.images[i])

digits.data[:5]

df = pd.DataFrame(digits.data)
df.head()

df['target'] = digits.target
df.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(['target'],axis='columns'),digits.target,test_size=0.2)

len(x_train)

len(x_test)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)

#n_estimator -> no. of random trees
#by default there are 10 Random trees
model.score(x_test,y_test)

y_predicted = model.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predicted)
cm

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sn
plt.figure(figsize=(10,7))
sn.heatmap(cm,annot=True)
plt.xlabel('Predicted',size=23)
plt.ylabel('Truth',size=25)